[project]
name = "steady-queue"
dynamic = ["version"]
description = "An asynchronous task library for Django that supports delayed tasks, concurrency controls, recurring tasks, pausing queues, numeric priorities per task, priorities by queue order and bulk enqueueing."
readme = "README.md"
authors = [
    { name = "Elias Hernandis", email = "elias@hernandis.me" }
]
requires-python = ">=3.13"
keywords = ["django", "tasks", "async", "jobs", "queues"]
classifiers = [
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
]
dependencies = [
    "crontab>=1.0.5",
    "django>=5.2,<6",
    "django-tasks>=0.8.1,<0.9.0",
]

[project.urls]
Homepage = "https://github.com/knifecake/steady-queue"
Source = "https://github.com/knifecake/steady-queue"
Documentation = "https://steady-queue.readthedocs.io/en/latest/"
Tracker = "https://github.com/knifecake/steady-queue/issues"
Releases = "https://github.com/knifecake/steady-queue/releases"

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py312"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["steady_queue*"]

[tool.setuptools.dynamic]
version = {attr = "steady_queue.__version__"}

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
warn_unused_ignores = true
warn_return_any = true
show_error_codes = true
# strict_optional = true
# implicit_optional = true
# disallow_subclassing_any = true
# disallow_untyped_calls = true
# disallow_untyped_defs = true
# disallow_incomplete_defs = true
# disallow_untyped_decorators = true
# check_untyped_defs = true
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "tests.settings"

[dependency-groups]
dev = [
    "coverage>=7.10.2",
    "django-environ>=0.12.0",
    "django-stubs-ext>=5.2.2",
    "django-stubs[compatible-mypy]>=5.2.2",
    "ipython>=9.4.0",
    "mypy>=1.17.1",
    "pre-commit>=4.0.1",
    "psycopg[binary,pool]>=3.2.6",
    "ruff>=0.11.6",
    "ty>=0.0.1a17",
    "types-python-crontab>=3.3.0.20250715",
]
