# Generated by Django 5.2 on 2025-04-24 12:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robust_queue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="class_name",
            field=models.CharField(max_length=255, verbose_name="class name"),
        ),
        migrations.AlterField(
            model_name="job",
            name="queue_name",
            field=models.CharField(max_length=255, verbose_name="queue name"),
        ),
        migrations.CreateModel(
            name="BlockedExecution",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "queue_name",
                    models.CharField(max_length=255, verbose_name="queue name"),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="priority")),
                (
                    "concurrency_key",
                    models.CharField(max_length=255, verbose_name="concurrency key"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_execution",
                        to="robust_queue.job",
                        verbose_name="job",
                    ),
                ),
            ],
            options={
                "verbose_name": "blocked execution",
                "verbose_name_plural": "blocked executions",
                "indexes": [
                    models.Index(
                        fields=["concurrency_key", "priority", "job"],
                        name="ix_rq_blocked_for_release",
                    ),
                    models.Index(
                        fields=["expires_at", "concurrency_key"],
                        name="ix_rq_blocked_for_maintenance",
                    ),
                ],
            },
        ),
    ]
