# Generated by Django 5.2 on 2025-04-24 12:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robust_queue", "0004_claimedexecution"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedExecution",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, null=True, verbose_name="error"),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failed_execution",
                        to="robust_queue.job",
                        verbose_name="job",
                    ),
                ),
            ],
            options={
                "verbose_name": "failed execution",
                "verbose_name_plural": "failed executions",
            },
        ),
    ]
