# Generated by Django 5.2 on 2025-04-24 12:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robust_queue', '0006_pause'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyExecution',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_name', models.CharField(max_length=255, verbose_name='queue name')),
                ('priority', models.IntegerField(default=0, verbose_name='priority')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ready_execution', to='robust_queue.job', verbose_name='job')),
            ],
            options={
                'verbose_name': 'ready execution',
                'verbose_name_plural': 'ready executions',
                'indexes': [models.Index(fields=['priority', 'job'], name='ix_rq_poll_all'), models.Index(fields=['queue_name', 'priority', 'created_at'], name='ix_rq_poll_for_queue')],
            },
        ),
    ]
