# Generated by Django 5.2 on 2025-04-24 12:54

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robust_queue", "0010_scheduledexecution"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semaphore",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=255, verbose_name="key")),
                ("value", models.IntegerField(default=1, verbose_name="value")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expires at"
                    ),
                ),
            ],
            options={
                "verbose_name": "semaphore",
                "verbose_name_plural": "semaphores",
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="ix_rq_semaphore_expires_at"
                    ),
                    models.Index(
                        fields=["key", "value"], name="ix_rq_semaphores_key_value"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("key",), name="uq_rq_semaphore_key")
                ],
            },
        ),
    ]
