# Generated by Django 5.2 on 2025-08-08 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robust_queue', '0012_alter_claimedexecution_process'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recurringexecution',
            name='uq_sq_recurring_task_run_at',
        ),
        migrations.RemoveField(
            model_name='recurringexecution',
            name='task_key',
        ),
        migrations.AddField(
            model_name='recurringexecution',
            name='task',
            field=models.ForeignKey(db_column='task_key', default='A', on_delete=django.db.models.deletion.PROTECT, to='robust_queue.recurringtask', to_field='key', verbose_name='task key'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='recurringexecution',
            constraint=models.UniqueConstraint(fields=('task', 'run_at'), name='uq_sq_recurring_task_run_at'),
        ),
    ]
