# Generated by Django 5.2 on 2025-08-09 22:27

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robust_queue", "0014_alter_recurringtask_arguments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="metadata",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="metadata",
            ),
        ),
        migrations.AlterField(
            model_name="recurringexecution",
            name="task",
            field=models.ForeignKey(
                db_column="task_key",
                on_delete=django.db.models.deletion.CASCADE,
                to="robust_queue.recurringtask",
                to_field="key",
                verbose_name="recurring task",
            ),
        ),
    ]
